centrifuge/pools-subql

package.json, schema.graphql, src/api-interfaces/lookup.ts, src/chaintypes.ts, src/mappings/blocks.ts, src/mappings/epochs.ts, src/mappings/pools.ts, src/mappings/tranches.ts, yarn.lock
- Adds indexing of token prices
- Adds indexing of token supplt
- Adds computation of daily and sinceInception yields (non annualized)
=> 20220608 Include EMBRIO.tech progress

project.yaml, schema.graphql, src/helpers/types.ts, src/mappings/handlers/poolsHandlers.ts, src/mappings/services/epochService.ts, src/mappings/services/investorTransactionService.ts, src/mappings/services/outstandingOrderService.ts, src/mappings/services/poolService.ts, src/mappings/services/trancheService.ts
Provides new features for investor transactions and outstanding orders. 
!!! Transaction fees not yet handled in investor transactions !!!
=> Implement single invest orders and outstanding orders

.github/workflows/deploy.yml, README.md, docker-compose.yml, docker/load-extensions.sh, docker/pg-Dockerfile, package.json, project.yaml, schema.graphql, src/helpers/paginatedGetter.ts, src/helpers/stateSnapshot.ts, src/helpers/types.ts, src/mappings/handlers/blockHandlers.ts, src/mappings/handlers/loansHandlers.ts, src/mappings/handlers/ormlTokensHandlers.ts, src/mappings/handlers/poolsHandlers.ts, src/mappings/handlers/proxyHandlers.ts, src/mappings/services/accountService.ts, src/mappings/services/borrowerTransactionService.ts, src/mappings/services/currencyBalance.ts, src/mappings/services/epochService.ts, src/mappings/services/investorTransactionService.ts, src/mappings/services/loanService.ts, src/mappings/services/outstandingOrderService.ts, src/mappings/services/poolService.ts, src/mappings/services/trancheBalanceService.ts, src/mappings/services/trancheService.ts, yarn.lock
Make sure to use
**indexer Image:** onfinality/subql-node:v1.9.2
**Query Image:** onfinality/subql-query:v1.4.0
- Extended indexed values for pools/tranches
- Handle pool update events
- Tracking loans history in snapshots
- Index of accounts and tranche balances
- index of currency balances
- Index of investor transactions
- Tranche selectors in UI
- Currency display in UI
=> 20221012 Integrate progress until sprint 13

project.yaml, src/mappings/handlers/loansHandlers.ts, src/mappings/services/epochService.ts
* chore: update dev for local environment
* fix: index investments and repayments in epoches
=> 137 sumborrowedamount and sumrepaidamount are not increasing (#138)

.github/workflows/subql_deploy_workflow.yaml, package.json, src/mappings/handlers/blockHandlers.ts, src/mappings/services/loanService.test.ts, src/mappings/services/loanService.ts, src/mappings/services/poolService.ts, yarn.lock
Temporary fix for https://github.com/embrio-tech/centrifuge-subql/issues/146
=> Fix for failing loan snapshots due to modified rates() method

.github/workflows/subql_deploy_workflow.yaml, chains/base.yaml, package.json, yarn.lock
Fixes the broken indexer on newer subql versions
=> chore: update subql version

.github/workflows/subql_deploy_workflow.yaml, .github/workflows/test.yml, chains/demo.yaml
Fixes the subql indexer for demo chain
=> fix: demo environment indexing

.github/workflows/subql_deploy_workflow.yaml, chains/base.yaml, src/helpers/errorHandler.ts, src/helpers/types.ts, src/mappings/handlers/investmentsHandlers.ts, src/mappings/handlers/loansHandlers.ts, src/mappings/handlers/ormlTokensHandlers.ts, src/mappings/handlers/poolsHandlers.ts
This reverts commit c2e8accf0d22ed67095dbf7461f1afb862f38202.
=> Revert "feat: transfer debt handler (#82)"

.envrc, chains-cfg/_root.yaml, chains-cfg/demo.yaml, chains-cfg/development.yaml, chains-evm/eth/centrifuge.yaml, chains-tinlake/centrifuge.yaml, package.json, project-generator.sh, schema.graphql, src/@types/gobal.d.ts, src/chaintypes.ts, src/helpers/stateSnapshot.ts, src/helpers/types.ts, src/index.ts, src/mappings/handlers/blockHandlers.ts, src/mappings/handlers/evmHandlers.ts, src/mappings/handlers/investmentsHandlers.ts, src/mappings/handlers/ormlTokensHandlers.ts, src/mappings/handlers/poolFeesHandlers.ts, src/mappings/handlers/poolsHandlers.ts, src/mappings/services/accountService.test.ts, src/mappings/services/accountService.ts, src/mappings/services/blockchainService.ts, src/mappings/services/currencyService.ts, src/mappings/services/epochService.ts, src/mappings/services/poolFeeService.ts, src/mappings/services/poolFeeTransactionService.ts, src/mappings/services/poolService.test.ts, src/mappings/services/poolService.ts, yarn.lock
⚠️  Use normal merge (No commit squash)
=> 20240226 Sprint 28

chains-tinlake/centrifuge.yaml, src/config.ts, src/mappings/handlers/ethHandlers.ts
* fix: incorrect TVL indexing tinlake
* Update chains-tinlake/centrifuge.yaml
=> fix: incorrect TVL indexing tinlake (#223)

src/chaintypes.ts, src/helpers/types.ts, src/mappings/handlers/blockHandlers.ts, src/mappings/handlers/ethHandlers.ts, src/mappings/handlers/evmHandlers.ts, src/mappings/services/poolFeeService.ts, src/mappings/services/poolService.ts, yarn.lock
* feat: poolFee Accruals
* fix: chaintypes for runtime upgrade
* fix: accruals logic
=> 218-track-poolFee-accruals (#224)

src/mappings/handlers/loansHandlers.ts
=> fix: activate on transfer debt

.prettierrc.js, schema.graphql, src/mappings/handlers/loansHandlers.ts, src/mappings/handlers/poolsHandlers.ts, src/mappings/services/assetService.ts, src/mappings/services/assetTransactionService.ts, src/mappings/services/poolService.ts, src/mappings/services/trancheBalanceService.ts, tsconfig.json
=> feat: track cash transfers as asset transaction type

src/config.ts, src/mappings/handlers/evmHandlers.ts
=> 153-ETH-indexer-fails-to-attach-LP-DynamicSource

schema.graphql, src/mappings/handlers/blockHandlers.ts, src/mappings/services/poolService.ts
=> feat: track total cash asset value in PoolSnapshot

.envrc.example, schema.graphql, src/mappings/handlers/poolFeesHandlers.ts, src/mappings/handlers/poolsHandlers.ts, src/mappings/services/assetTransactionService.ts, src/mappings/services/epochService.ts
=> feat: track investments and redemptions in onchain cash asset

jest/globals.js, package.json, src/helpers/types.ts, src/mappings/handlers/loansHandlers.ts, src/mappings/services/assetService.ts, src/mappings/services/trancheService.test.ts, yarn.lock
=> feat: add missing quantity settlement price for handleLoanDebtTransferred1024

schema.graphql, src/mappings/handlers/loansHandlers.ts, src/mappings/services/assetPositionService.ts, src/mappings/services/assetTransactionService.ts, src/mappings/services/poolService.ts
=> feat: add AssetPosition entity and track realized p&l

src/helpers/types.ts, src/mappings/handlers/oracleHandlers.ts
=> feat: track oracle transactions

schema.graphql, src/mappings/handlers/blockHandlers.ts, src/mappings/services/trancheService.ts
=> feat: add yieldMTD, yieldQTD, yieldYTD

src/helpers/types.ts, src/mappings/handlers/blockHandlers.ts, src/mappings/services/assetService.ts, src/mappings/services/poolService.ts
=> fix: support assets without maturity

src/mappings/handlers/ethHandlers.ts, src/mappings/services/poolService.ts
=> 209-Normalization-required-for-getting-TVL-per-day-in-1-query

.github/workflows/test.yml, jest.smoke.config.ts, jest/smoke.js, package.json, smoke-tests/global.d.ts, smoke-tests/snapshots.test.ts, smoke-tests/timekeeper.test.ts, smoke-tests/tvl.test.ts, tsconfig.json
This introduces some basic checks. More tests are however required for invariants for each pool.
=> 195-Integration-tests-invariants

src/helpers/stateSnapshot.ts, src/mappings/handlers/poolsHandlers.ts, src/mappings/services/poolFeeService.ts
=> fix: wrong poolFees historical values
